using CompoundSuitabilitySummaryResults15 = PerkinElmer.Simplicity.Data.Version15.DataEntities.Chromatography.CompoundSuitabilitySummaryResults;
using CompoundSuitabilitySummaryResults16 = PerkinElmer.Simplicity.Data.Version16.DataEntities.Chromatography.CompoundSuitabilitySummaryResults;

namespace PerkinElmer.Simplicity.DataTransform.V15ToV16.TansformEntities.Chromatography
{
    public class CompoundSuitabilitySummaryResults
    {
        public static CompoundSuitabilitySummaryResults16 Transform(
            CompoundSuitabilitySummaryResults15 compoundSuitabilitySummaryResults)
        {
            if (compoundSuitabilitySummaryResults == null) return null;
            return new CompoundSuitabilitySummaryResults16
            {
                Id = compoundSuitabilitySummaryResults.Id,
                AnalysisResultSetId = compoundSuitabilitySummaryResults.AnalysisResultSetId,
                CompoundGuid = compoundSuitabilitySummaryResults.CompoundGuid,
                AreaAverage = compoundSuitabilitySummaryResults.AreaAverage,
                AreaStDev = compoundSuitabilitySummaryResults.AreaStDev,
                AreaRelativeStdDevPercent = compoundSuitabilitySummaryResults.AreaRelativeStdDevPercent,
                AreaRelativeStdDevPassed = compoundSuitabilitySummaryResults.AreaRelativeStdDevPassed,
                AreaFailureReason = compoundSuitabilitySummaryResults.AreaFailureReason,
                HeightAverage = compoundSuitabilitySummaryResults.HeightAverage,
                HeightStDev = compoundSuitabilitySummaryResults.HeightStDev,
                HeightRelativeStdDevPercent = compoundSuitabilitySummaryResults.HeightRelativeStdDevPercent,
                HeightRelativeStdDevPassed = compoundSuitabilitySummaryResults.HeightRelativeStdDevPassed,
                HeightFailureReason = compoundSuitabilitySummaryResults.HeightFailureReason,
                TheoreticalPlatesNAverage = compoundSuitabilitySummaryResults.TheoreticalPlatesNAverage,
                TheoreticalPlatesNStDev = compoundSuitabilitySummaryResults.TheoreticalPlatesNStDev,
                TheoreticalPlatesNRelativeStdDevPercent = compoundSuitabilitySummaryResults.TheoreticalPlatesNRelativeStdDevPercent,
                TheoreticalPlatesNRelativeStdDevPassed = compoundSuitabilitySummaryResults.TheoreticalPlatesNRelativeStdDevPassed,
                TheoreticalPlatesNFailureReason = compoundSuitabilitySummaryResults.TheoreticalPlatesNFailureReason,
                TheoreticalPlatesNTanAverage = compoundSuitabilitySummaryResults.TheoreticalPlatesNTanAverage,
                TheoreticalPlatesNTanStDev = compoundSuitabilitySummaryResults.TheoreticalPlatesNTanStDev,
                TheoreticalPlatesNTanRelativeStdDevPercent = compoundSuitabilitySummaryResults.TheoreticalPlatesNTanRelativeStdDevPercent,
                TheoreticalPlatesNTanRelativeStdDevPassed = compoundSuitabilitySummaryResults.TheoreticalPlatesNTanRelativeStdDevPassed,
                TheoreticalPlatesNTanFailureReason = compoundSuitabilitySummaryResults.TheoreticalPlatesNTanFailureReason,
                //TODO:The default values for properties below.
                TheoreticalPlatesNFoleyDorseyAverage = null,
                TheoreticalPlatesNFoleyDorseyStDev = null,
                TheoreticalPlatesNFoleyDorseyRelativeStdDevPercent = null,
                TheoreticalPlatesNFoleyDorseyRelativeStdDevPassed = null,
                TheoreticalPlatesNFoleyDorseyFailureReason = 0,
                TailingFactorSymmetryAverage = compoundSuitabilitySummaryResults.TailingFactorSymmetryAverage,
                TailingFactorSymmetryStDev = compoundSuitabilitySummaryResults.TailingFactorSymmetryStDev,
                TailingFactorSymmetryRelativeStdDevPercent = compoundSuitabilitySummaryResults.TailingFactorSymmetryRelativeStdDevPercent,
                TailingFactorSymmetryRelativeStdDevPassed = compoundSuitabilitySummaryResults.TailingFactorSymmetryRelativeStdDevPassed,
                TailingFactorSymmetryFailureReason = compoundSuitabilitySummaryResults.TailingFactorSymmetryFailureReason,
                RelativeRetentionAverage = compoundSuitabilitySummaryResults.RelativeRetentionAverage,
                RelativeRetentionStDev = compoundSuitabilitySummaryResults.RelativeRetentionStDev,
                RelativeRetentionRelativeStdDevPercent = compoundSuitabilitySummaryResults.RelativeRetentionRelativeStdDevPercent,
                RelativeRetentionRelativeStdDevPassed = compoundSuitabilitySummaryResults.RelativeRetentionRelativeStdDevPassed,
                RelativeRetentionFailureReason = compoundSuitabilitySummaryResults.RelativeRetentionFailureReason,
                RelativeRetentionTimeAverage = compoundSuitabilitySummaryResults.RelativeRetentionTimeAverage,
                RelativeRetentionTimeStDev = compoundSuitabilitySummaryResults.RelativeRetentionTimeStDev,
                RelativeRetentionTimeRelativeStdDevPercent = compoundSuitabilitySummaryResults.RelativeRetentionTimeRelativeStdDevPercent,
                RelativeRetentionTimeRelativeStdDevPassed = compoundSuitabilitySummaryResults.RelativeRetentionTimeRelativeStdDevPassed,
                RelativeRetentionTimeFailureReason = compoundSuitabilitySummaryResults.RelativeRetentionTimeFailureReason,
                RetentionTimeAverage = compoundSuitabilitySummaryResults.RetentionTimeAverage,
                RetentionTimeStDev = compoundSuitabilitySummaryResults.RetentionTimeStDev,
                RetentionTimeRelativeStdDevPercent = compoundSuitabilitySummaryResults.RetentionTimeRelativeStdDevPercent,
                RetentionTimeRelativeStdDevPassed = compoundSuitabilitySummaryResults.RetentionTimeRelativeStdDevPassed,
                RetentionTimeFailureReason = compoundSuitabilitySummaryResults.RetentionTimeFailureReason,
                CapacityFactorKPrimeAverage = compoundSuitabilitySummaryResults.CapacityFactorKPrimeAverage,
                CapacityFactorKPrimeStDev = compoundSuitabilitySummaryResults.CapacityFactorKPrimeStDev,
                CapacityFactorKPrimeRelativeStdDevPercent = compoundSuitabilitySummaryResults.CapacityFactorKPrimeRelativeStdDevPercent,
                CapacityFactorKPrimeRelativeStdDevPassed = compoundSuitabilitySummaryResults.CapacityFactorKPrimeRelativeStdDevPassed,
                CapacityFactorKPrimeFailureReason = compoundSuitabilitySummaryResults.CapacityFactorKPrimeFailureReason,
                ResolutionAverage = compoundSuitabilitySummaryResults.ResolutionAverage,
                ResolutionStDev = compoundSuitabilitySummaryResults.ResolutionStDev,
                ResolutionRelativeStdDevPercent = compoundSuitabilitySummaryResults.ResolutionRelativeStdDevPercent,
                ResolutionRelativeStdDevPassed = compoundSuitabilitySummaryResults.ResolutionRelativeStdDevPassed,
                ResolutionFailureReason = compoundSuitabilitySummaryResults.ResolutionFailureReason,
                UspResolutionAverage = compoundSuitabilitySummaryResults.UspResolutionAverage,
                UspResolutionStDev = compoundSuitabilitySummaryResults.UspResolutionStDev,
                UspResolutionRelativeStdDevPercent = compoundSuitabilitySummaryResults.UspResolutionRelativeStdDevPercent,
                UspResolutionRelativeStdDevPassed = compoundSuitabilitySummaryResults.UspResolutionRelativeStdDevPassed,
                UspResolutionFailureReason = compoundSuitabilitySummaryResults.UspResolutionFailureReason,
                SignalToNoiseAverage = compoundSuitabilitySummaryResults.SignalToNoiseAverage,
                SignalToNoiseStDev = compoundSuitabilitySummaryResults.SignalToNoiseStDev,
                SignalToNoiseRelativeStdDevPercent = compoundSuitabilitySummaryResults.SignalToNoiseRelativeStdDevPercent,
                SignalToNoiseRelativeStdDevPassed = compoundSuitabilitySummaryResults.SignalToNoiseRelativeStdDevPassed,
                SignalToNoiseFailureReason = compoundSuitabilitySummaryResults.SignalToNoiseFailureReason,
                PeakWidthAtBaseAverage = compoundSuitabilitySummaryResults.PeakWidthAtBaseAverage,
                PeakWidthAtBaseStDev = compoundSuitabilitySummaryResults.PeakWidthAtBaseStDev,
                PeakWidthAtBaseRelativeStdDevPercent = compoundSuitabilitySummaryResults.PeakWidthAtBaseRelativeStdDevPercent,
                PeakWidthAtBaseRelativeStdDevPassed = compoundSuitabilitySummaryResults.PeakWidthAtBaseRelativeStdDevPassed,
                PeakWidthAtBaseFailureReason = compoundSuitabilitySummaryResults.PeakWidthAtBaseFailureReason,
                PeakWidthAt5PctAverage = compoundSuitabilitySummaryResults.PeakWidthAt5PctAverage,
                PeakWidthAt5PctStDev = compoundSuitabilitySummaryResults.PeakWidthAt5PctStDev,
                PeakWidthAt5PctRelativeStdDevPercent = compoundSuitabilitySummaryResults.PeakWidthAt5PctRelativeStdDevPercent,
                PeakWidthAt5PctRelativeStdDevPassed = compoundSuitabilitySummaryResults.PeakWidthAt5PctRelativeStdDevPassed,
                PeakWidthAt5PctFailureReason = compoundSuitabilitySummaryResults.PeakWidthAt5PctFailureReason,
                PeakWidthAt10PctAverage = compoundSuitabilitySummaryResults.PeakWidthAt10PctAverage,
                PeakWidthAt10PctStDev = compoundSuitabilitySummaryResults.PeakWidthAt10PctStDev,
                PeakWidthAt10PctRelativeStdDevPercent = compoundSuitabilitySummaryResults.PeakWidthAt10PctRelativeStdDevPercent,
                PeakWidthAt10PctRelativeStdDevPassed = compoundSuitabilitySummaryResults.PeakWidthAt10PctRelativeStdDevPassed,
                PeakWidthAt10PctFailureReason = compoundSuitabilitySummaryResults.PeakWidthAt10PctFailureReason,
                PeakWidthAt50PctAverage = compoundSuitabilitySummaryResults.PeakWidthAt50PctAverage,
                PeakWidthAt50PctStDev = compoundSuitabilitySummaryResults.PeakWidthAt50PctStDev,
                PeakWidthAt50PctRelativeStdDevPercent = compoundSuitabilitySummaryResults.PeakWidthAt50PctRelativeStdDevPercent,
                PeakWidthAt50PctRelativeStdDevPassed = compoundSuitabilitySummaryResults.PeakWidthAt50PctRelativeStdDevPassed,
                PeakWidthAt50PctFailureReason = compoundSuitabilitySummaryResults.PeakWidthAt50PctFailureReason,
                SstFlag = compoundSuitabilitySummaryResults.SstFlag
            };
        }
    }
}
