using RunPeakResult15 = PerkinElmer.Simplicity.Data.Version15.Contract.DataEntities.Chromatography.RunPeakResult;
using RunPeakResult16 = PerkinElmer.Simplicity.Data.Version16.Contract.DataEntities.Chromatography.RunPeakResult;

namespace PerkinElmer.Simplicity.DataTransform.V15ToV16.TansformEntities.Chromatography
{
    public class RunPeakResult
    {
        public static RunPeakResult16 Transform(RunPeakResult15 runPeakResult)
        {
            if (runPeakResult == null) return null;
            return new RunPeakResult16
            {
                Id = runPeakResult.Id,
                CalculatedChannelDataId = runPeakResult.CalculatedChannelDataId,
                BatchRunChannelGuid = runPeakResult.BatchRunChannelGuid,
                CompoundGuid = runPeakResult.CompoundGuid,
                ChannelGuid = runPeakResult.ChannelGuid,
                PeakNumber = runPeakResult.PeakNumber,
                Area = runPeakResult.Area,
                Height = runPeakResult.Height,
                InternalStandardAreaRatio = runPeakResult.InternalStandardAreaRatio,
                InternalStandardHeightRatio = runPeakResult.InternalStandardHeightRatio,
                AreaPercent = runPeakResult.AreaPercent,
                RetentionTime = runPeakResult.RetentionTime,
                StartPeakTime = runPeakResult.StartPeakTime,
                EndPeakTime = runPeakResult.EndPeakTime,
                BaselineSlope = runPeakResult.BaselineSlope,
                BaselineIntercept = runPeakResult.BaselineIntercept,
                SignalToNoiseRatio = runPeakResult.SignalToNoiseRatio,
                Amount = runPeakResult.Amount,
                InternalStandardAmountRatio = runPeakResult.AreaToAmountRatio,
                AreaToHeightRatio = runPeakResult.AreaToHeightRatio,
                BaselineCode = runPeakResult.BaselineCode,
                CalibrationInRange = runPeakResult.CalibrationInRange,
                PeakGroupGuid = runPeakResult.PeakGroupGuid,
                PeakName = runPeakResult.PeakName,
                PeakGroup = runPeakResult.PeakGroup,
                Overlapped = runPeakResult.Overlapped,
                IsBaselineExpo = runPeakResult.IsBaselineExpo,
                ExpoA = runPeakResult.ExpoA,
                ExpoB = runPeakResult.ExpoB,
                ExpoCorrection = runPeakResult.ExpoCorrection,
                ExpoDecay = runPeakResult.ExpoDecay,
                RetTimeReferenceGuid = runPeakResult.RetTimeReferenceGuid,
                RrtReferenceGuid = runPeakResult.RrtReferenceGuid,
                InternalStandardGuid = runPeakResult.InternalStandardGuid,
                KPrime = runPeakResult.KPrime,
                NormalizedAmount = runPeakResult.NormalizedAmount,
                RelativeRetentionTime = runPeakResult.RelativeRetentionTime,
                RawAmount = runPeakResult.RawAmount,
                TailingFactor = runPeakResult.TailingFactor,
                Resolution = runPeakResult.Resolution,
                PeakWidth = runPeakResult.PeakWidth,
                PeakWidthAtHalfHeight = runPeakResult.PeakWidthAtHalfHeight,
                PlatesDorseyFoley = runPeakResult.PlatesDorseyFoley,
                PlatesTangential = runPeakResult.PlatesTangential,
                PeakWidthAt5PercentHeight = runPeakResult.PeakWidthAt5PercentHeight,
                PeakWidthAt10PercentHeight = runPeakResult.PeakWidthAt10PercentHeight,
                RelativeRetTimeSuit = runPeakResult.RelativeRetTimeSuit,
                Signal = runPeakResult.Signal,
                ExpoHeight = runPeakResult.ExpoHeight,
                PeakGuid = runPeakResult.PeakGuid,
                InternalStandardAmount = runPeakResult.InternalStandardAmount,
                ReferenceInternalStandardCompoundGuid = runPeakResult.ReferenceInternalStandardCompoundGuid,
                AmountError = runPeakResult.AmountError,
                CompoundType = runPeakResult.CompoundType,
                AbsorbanceRatio = runPeakResult.AbsorbanceRatio,
                StandardConfirmationIndex = runPeakResult.StandardConfirmationIndex,
                StandardConfirmationPassed = runPeakResult.StandardConfirmationPassed,
                StandardConfirmationError = runPeakResult.StandardConfirmationError,
                WavelengthMax = runPeakResult.WavelengthMax,
                AbsorbanceAtWavelengthMax = runPeakResult.AbsorbanceAtWavelengthMax,
                WavelengthMaxError = runPeakResult.WavelengthMaxError,
                PeakPurity = runPeakResult.PeakPurity,
                PeakPurityPassed = runPeakResult.PeakPurityPassed,
                PeakPurityError = runPeakResult.PeakPurityError,
                DataSourceType = runPeakResult.DataSourceType,
                AbsorbanceRatioError = runPeakResult.AbsorbanceRatioError,
                ManuallyOverriden = runPeakResult.ManuallyOverriden,
                MidIndex = runPeakResult.MidIndex,
                StartIndex = runPeakResult.StartIndex,
                StopIndex = runPeakResult.StopIndex,
                LibraryCompound = runPeakResult.LibraryCompound,
                SearchLibraryCompound = runPeakResult.SearchLibraryCompound,
                HitQualityValue = runPeakResult.HitQualityValue,
                SearchMatch = runPeakResult.SearchMatch,
                LibraryName = runPeakResult.LibraryName,
                SearchLibrary = runPeakResult.SearchLibrary,
                LibraryGuid = runPeakResult.LibraryGuid,
                LibraryConfirmation = runPeakResult.LibraryConfirmation,
                CompoundAssignmentType = runPeakResult.CompoundAssignmentType
            };
        }
    }
}
