using System;
using System.Collections.Generic;

namespace PerkinElmer.Simplicity.Data.Version16.DataEntities.Chromatography.ProcessingMethod
{
    public class ChannelMethod
    {
	    public ChannelMethod()
	    {
			IntegrationEvents = new List<IntegrationEvent>();
	    }
        public long Id { get; set; }

        public Guid ChannelGuid { get; set; }
        public Guid ParentChannelGuid { get; set; }
        public long ProcessingMethodId { get; set; }

        public int ChannelIndex { get; set; }
        
        public List<IntegrationEvent> IntegrationEvents { get; set; }

	    public double TimeAdjustment { get; set; }

	    public double TangentSkimWidth { get; set; }

	    public Guid RrtReferenceCompound { get; set; }

	    public short RrtReferenceType { get; set; }

		public int SmoothFunction { get; set; }

	    public int SmoothWidth { get; set; }

	    public int SmoothPasses { get; set; }

	    public int SmoothOrder { get; set; }

	    public int SmoothCycles { get; set; }

		public int? BunchingFactor { get; set; }

		public double? NoiseThreshold { get; set; }

		public double? AreaThreshold { get; set; }

	    public double WidthRatio { get; set; }

	    public double ValleyToPeakRatio { get; set; }

	    public double PeakHeightRatio { get; set; }

	    public double AdjustedHeightRatio { get; set; }

	    public double ValleyHeightRatio { get; set; }

	    public double VoidTime { get; set; }

	    public short VoidTimeType { get; set; }
	    public Guid SubtractedBlankOrigBatchRunGuid { get; set; }
		public string ChromatographicChannelDescriptor { get; set; }
	    public bool IsPdaMethod { get; set; }
	    public PdaPeakPurityParameters PdaPeakPurityParameters { get; set; }
	    public PdaWavelengthMaxParameters PdaWavelengthMaxParameters { get; set; }
	    public PdaAbsorbanceRatioParameters PdaAbsorbanceRatioParameters { get; set; }
	    public PdaBaselineCorrectionParameters PdaBaselineCorrectionParameters { get; set; }
	    public PdaStandardConfirmationParameters PdaStandardConfirmationParameters { get; set; }
	    public PdaLibrarySearchParameters PdaLibrarySearchParameters { get; set; }
	    public PdaLibraryConfirmationParameters PdaLibraryConfirmationParameters { get; set; }
	    public SuitabilityParameters SuitabilityParameters { get; set; }
	    public string ProcessingMethodChannelIdentifier { get; set; }
		public bool AutoGeneratedFromData { get; set; }
	}
}
